[versions]
ktlint = "1.5.0"

gradle-plugin = "9.2.1"

androidx-appcompat = "1.7.1"

androidx-core = "1.9.0"
androidx-lifecycle = "2.11.0"
androidx-navigation = "2.9.8"
androidx-room = "2.8.4"
androidx-sqlite = "2.7.0"
androidx-test-ext = "1.3.0"

jetbrains-dokka = "2.2.0"
jetbrains-kotlin = "2.3.21"

io-mockk = "1.14.11"

google-devtools-ksp = "2.3.10"

squareup-kotlinpoet = "2.3.0"
google-auto-service = "1.1.1"

kotlin-compile-testing = "0.8.0"

junit5 = "6.1.2"

[plugins]
android-junit5 = { id = "de.mannodermaus.android-junit5", version = "2.0.1" }
google-devtools-ksp = { id = "com.google.devtools.ksp", version.ref = "google-devtools-ksp" }

[libraries]
timber = { module = "com.jakewharton.timber:timber", version = "5.0.1" }
junit = { module ="junit:junit", version = "4.13.2" }
junit5-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit5-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }

android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "gradle-plugin" }

androidx-activity = { module = "androidx.activity:activity", version = "1.13.0" }
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version = "1.13.0" }

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-appcompatResources = { module = "androidx.appcompat:appcompat-resources", version.ref = "androidx-appcompat" }

androidx-constraintLayout = "androidx.constraintlayout:constraintlayout:2.2.1"

androidx-fragment = { module = "androidx.fragment:fragment", version = "1.8.9" }
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version = "1.8.9" }

androidx-lifecycle-extensions = { module = "androidx.lifecycle:lifecycle-extensions", version = "2.2.0" }
androidx-lifecycle-runTime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-liveData-ktx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-liveDataCore-ktx = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version.ref = "androidx-lifecycle" }

androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "androidx-navigation" }
androidx-navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "androidx-navigation" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-common = { module = "androidx.room:room-common", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }

androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidx-sqlite" }
androidx-sqlite-ktx = { module = "androidx.sqlite:sqlite-ktx", version.ref = "androidx-sqlite" }

androidx-test-core = { module = "androidx.test:core", version = "1.7.0" }
androidx-test-core-ktx = { module = "androidx.test:core-ktx", version = "1.7.0" }
androidx-test-runner = { module = "androidx.test:runner", version = "1.7.0" }
androidx-test-rules = { module = "androidx.test:rules", version = "1.7.0" }

androidx-junitKtx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext" }

google-auto-service = { module = "com.google.auto.service:auto-service-annotations", version.ref = "google-auto-service" }
auto-service-ksp = "dev.zacsweers.autoservice:auto-service-ksp:1.2.0"
google-android-material = "com.google.android.material:material:1.14.0"

jetbrains-dokka-gradle = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "jetbrains-dokka" }
jetbrains-kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "jetbrains-kotlin" }

mockk = { module = "io.mockk:mockk", version.ref = "io-mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "io-mockk" }

spotless-gradle = "com.diffplug.spotless:spotless-plugin-gradle:8.8.0"

squareup-kotlinpoet = { module = "com.squareup:kotlinpoet", version.ref = "squareup-kotlinpoet" }
squareup-kotlinpoet-ksp = { module = "com.squareup:kotlinpoet-ksp", version.ref = "squareup-kotlinpoet" }

google-devtools-ksp = { module = "com.google.devtools.ksp:symbol-processing", version.ref = "google-devtools-ksp" }
google-devtools-ksp-api = { module = "com.google.devtools.ksp:symbol-processing-api", version.ref = "google-devtools-ksp" }

gradle-plugins-android-junit5 = "de.mannodermaus.gradle.plugins:android-junit5:2.0.1"
kotlin-compile-testing = { module = "dev.zacsweers.kctfork:core", version.ref = "kotlin-compile-testing" }
kotlin-compile-testing-ksp = { module = "dev.zacsweers.kctfork:ksp", version.ref ="kotlin-compile-testing" }
pintrest-ktlint = { module = "com.pinterest:ktlint", version.ref = "ktlint" }
