[versions]
ktlint = "0.40.0"

gradle-plugin = "7.3.1"

androidx-appcompat = "1.4.0-rc01"

androidx-core = "1.9.0"
androidx-lifecycle = "2.4.0"
androidx-navigation = "2.3.5"
androidx-room = "2.2.6"
androidx-sqlite = "2.1.0"
androidx-test = "1.5.0"
androidx-test-ext = "1.1.2"

jetbrains-dokka = "1.7.20"
jetbrains-kotlin = "1.7.21"

io-mockk = "1.13.3"

[libraries]
timber = "com.jakewharton.timber:timber:5.0.1"
junit = "junit:junit:4.13.2"

android-gradle-plugin = { module = "com.android.tools.build:gradle", version.ref = "gradle-plugin" }

androidx-activityKtx = "androidx.activity:activity-ktx:1.4.0"

androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "androidx-appcompat" }
androidx-appcompatResources = { module = "androidx.appcompat:appcompat-resources", version.ref = "androidx-appcompat" }

androidx-constraintLayout = "androidx.constraintlayout:constraintlayout:2.1.1"

androidx-fragmentKtx = "androidx.fragment:fragment-ktx:1.3.0"

androidx-lifecycle-extensions = "androidx.lifecycle:lifecycle-extensions:2.2.0"
androidx-lifecycle-runTimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-liveDataKtx = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidx-lifecycle" }
androidx-lifecycle-liveDataCoreKtx = { module = "androidx.lifecycle:lifecycle-livedata-core-ktx", version.ref = "androidx-lifecycle" }

androidx-navigation-fragmentKtx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "androidx-navigation" }
androidx-navigation-uiKtx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "androidx-navigation" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "androidx-room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "androidx-room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "androidx-room" }

androidx-sqlite = { module = "androidx.sqlite:sqlite", version.ref = "androidx-sqlite" }
androidx-sqliteKtx = { module = "androidx.sqlite:sqlite-ktx", version.ref = "androidx-sqlite" }


androidx-test-core = { module = "androidx.test:core", version.ref = "androidx-test" }
androidx-test-coreKtx = { module = "androidx.test:core-ktx", version.ref = "androidx-test" }
androidx-test-runner = { module = "androidx.test:runner", version.ref = "androidx-test" }
androidx-test-rules = { module = "androidx.test:rules", version.ref = "androidx-test" }

androidx-junitKtx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx-test-ext" }

google-auto-service = "com.google.auto.service:auto-service:1.0.1"
google-android-material = "com.google.android.material:material:1.5.0-alpha05"

jetbrains-dokka-gradle = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "jetbrains-dokka" }
jetbrains-kotlin-stdlib-jdk8 = { module = "org.jetbrains.kotlin:kotlin-stdlib-jdk8", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "jetbrains-kotlin" }
jetbrains-kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "jetbrains-kotlin" }

mockk = { module = "io.mockk:mockk", version.ref = "io-mockk" }
mockk-android = { module = "io.mockk:mockk-android", version.ref = "io-mockk" }

gradle-versions = "com.github.ben-manes:gradle-versions-plugin:0.44.0"

spotless-gradle = "com.diffplug.spotless:spotless-plugin-gradle:5.12.1"

squareup-kotlinpoet = "com.squareup:kotlinpoet:1.10.2"