name: auto-approve
on: pull_request_target

jobs:
  auto-approve:
    name: Auto-approve pull requests
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - uses: hmarr/auto-approve-action@v4
